events {
    worker_connections 1024;
}

http {
    upstream password_checker {
        server password-checker:8001;
    }

    upstream password_logger {
        server password-logger:8002;
    }

    server {
        listen 80;
        server_name localhost;

        # Прокси для сервиса проверки паролей
        location /check/ {
            proxy_pass http://password_checker/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Прокси для сервиса логирования
        location /log/ {
            proxy_pass http://password_logger/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Health checks
        location /health-checker {
            proxy_pass http://password_checker/health;
        }

        location /health-logger {
            proxy_pass http://password_logger/health;
        }
    }
}